### ISSUE TITLE
Evaluation numbers not completely matching github or paper results

### ISSUE THREAD

**Issue by mz32-personal** [3dlg-hcvc/OPDMulti#2]
Hello,

I have been trying to reproduce the results for OPDFormer-C, but am having trouble getting a matching results. 
I am using the pretrained weights for OPDFormer-C on OPDMulti RGB and the following command to run evaluation:
`python evaluate_on_log.py --config-file configs/opd_c_real.yaml --output-dir my_output_path --data-path path_to_data/OPDMulti/MotionDataset_h5 --input-format RGB --model_attr_path path_to_data/OPDMulti/obj_info.json --opts MODEL.WEIGHTS opdmulti_opdformer_c_rgb.pth DATASETS.TEST "('MotionNet_valid',)"`
 
The following are the results for bbox using the above command:
[04/25 00:39:26] d2.evaluation.evaluator INFO: Evaluation results for bbox: 
|  AP_pc  |  AP50_pc  |  AP75_pc  |  all_motion50_pc  |  motion_type50_mt  |  motion_origin50_mt  |  motion_axis50_mt  |
|:-------:|:---------:|:---------:|:-----------------:|:------------------:|:--------------------:|:------------------:|
| 20.094  |  31.556   |  22.390   |      12.768       |       29.230       |        38.637        |       17.786       |

I am interpreting PDet = AP50_c, +M = motion_type50_mt, +MA = motion_axis50_mt, and +MAO = all_motion50_pc. However, with this interpretation the value for +MA is quite off from the number in the paper, which I have included below. 

![Screen Shot 2023-04-25 at 10 54 31 AM](https://user-images.githubusercontent.com/92341156/234334030-6952d722-86ba-40b0-80b4-692198798c00.png)

According to this table (Table 3), +MA should be around 13.1. Am I missing a setting in my command or is my interpretation of the results off? If my interpretation is off, where can I find the results for PDet, +M, +MA, and +MAO? 

The other numbers are closer to the paper values, but not within the margins listed. Is this within expected behavior?

I have also tried to compare to the numbers listed on github, but neither the evaluation on test nor validation seems to match. 

GitHub:
![Screen Shot 2023-04-25 at 12 52 07 AM](https://user-images.githubusercontent.com/92341156/234335812-26d0fecc-4e9c-4a5a-aeb9-cdfdcbc8f73b.png)

Validation:
[04/25 00:39:26] d2.evaluation.evaluator INFO: Evaluation results for bbox: 
|  AP_pc  |  AP50_pc  |  AP75_pc  |  all_motion50_pc  |  motion_type50_mt  |  motion_origin50_mt  |  motion_axis50_mt  |
|:-------:|:---------:|:---------:|:-----------------:|:------------------:|:--------------------:|:------------------:|
| 20.094  |  31.556   |  22.390   |      12.768       |       29.230       |        38.637        |       17.786       |

Test:
[04/25 00:09:28] d2.evaluation.evaluator INFO: Evaluation results for bbox: 
|  AP_pc  |  AP50_pc  |  AP75_pc  |  all_motion50_pc  |  motion_type50_mt  |  motion_origin50_mt  |  motion_axis50_mt  |
|:-------:|:---------:|:---------:|:-----------------:|:------------------:|:--------------------:|:------------------:|
| 18.413  |  29.463   |  20.017   |       8.129       |       19.651       |        24.588        |       11.087       |

**Questions:**

- Am I missing a setting in my command? 
- Is my interpretation of the results off?
- If my interpretation is off, where can I find the results for PDet, +M, +MA, and +MAO? 
- Is it within expected behavior for the PDet, +M, +MA, and +MAO results to not be within the margins listed in the paper?
- Are the listed numbers on github on the validation or on the test set?

Thank you

**Comment by Sun-XH** [comment]
Hi there,

Thanks for the interest of our paper and project. From the results you showed, it is similar to our results in both paper and repo README. It's just the metrics you choose is not what we used in our results.

In the log, you can see something like following (there will be a lot of lines of different metrics, I just pick some for example):
```
[03/05 04:57:14] d2.evaluation.evaluator INFO:  Average Precision (Detection) (mAP_Detection) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.203
[03/05 04:57:14] d2.evaluation.evaluator INFO:  Average Precision (Detection) (mAP_Detection) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.319
[03/05 04:57:14] d2.evaluation.evaluator INFO:  Average Precision (Detection) (mAP_Detection) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.228
[03/05 04:57:14] d2.evaluation.evaluator INFO:  Average Precision (Detection) (mAP_Detection) @[ IoU=0.95      | area=   all | maxDets=100 ] = 0.008
```
So, we pick PDet, +M, +MA, +MAO from the following metrics:
**PDet**
```
Average Precision (Detection) (mAP_Detection) @[ IoU=0.50      | area=   all | maxDets=100 ]
```
**+M**
```
Average Precision (Motion Type Threshold) (mAP_Type) @[ IoU=0.50      | area=   all | maxDets=100 ]
```
**+MA**
```
Average Precision (+MA) Threshold) (mAP_+MA) @[ IoU=0.50      | area=   all | maxDets=100 ]
```
**+MAO**
```
Average Precision (All motion) Threshold) (mAP_Motion) @[ IoU=0.50      | area=   all | maxDets=100 ]
```

If you pick these metrics to compare, I think you will get the similar results.
