### ISSUE TITLE
How to implement the animation effect as shown in project page~

### ISSUE THREAD

**Issue by YZsZY** [3dlg-hcvc/OPDMulti#7]
Hello author~ I'd like to ask how to implement the animation effect as shown below:
![187-0](https://github.com/3dlg-hcvc/OPDMulti/assets/117158282/421c7d7e-da42-478b-b915-d18754016073)
Mainly, I wonder whether the input for training is RGB or RGBD, and how to select the region and get it to move. Looking forward to your reply~

**Comment by Sun-XH** [comment]
Hi,

Thanks for your interest in our work! We need the depth information to implement this animation. We use the RGB and GT depth image to convert the scene to point cloud. Then, we use the predicted openable part mask to get the points that belong to the openable part and manipulate the parts using the predicted motion parameters.

Hope this answer sovles your issue! If you have any further questions, feel free to ask.
